### PR TITLE
scrollTo() method

### PR DESCRIPTION
**Pull request by roszpun**
I had to remove old repo. Here is new pull request with fixed code.

### CODE REVIEW

**Comment by DominikSerafin** [comment]
Thanks! I'll merge it after some tests and documenting that feature on site

**Comment by DominikSerafin** [comment]
Hi again,

After some planning I've decided to introduce this feature in Vuebar 2.1 release. So when I'll finalize Vuebar 2.0 release then I'll merge this PR.

https://github.com/DominikSerafin/vuebar/projects/1

**Comment by mlg-ipleic** [comment]
When is next release?

**Comment by DominikSerafin** [comment]
@mlg-ipleic 

https://github.com/DominikSerafin/vuebar/issues/32#issuecomment-335397606

**Comment by JohnRSim** [comment]
ERROR in static/js/vendor.23cf009c84b9d066de57.js from UglifyJs
Unexpected token: name (calculate) [./node_modules/vuebar/vuebar.js:348,0][static/js/vendor.23cf009c84b9d066de57.js:12416,16]

I got this error when running the vuejs build on the fixes above by roszpun.
but works fine in dev mode..

**Comment by JohnRSim** [comment]
ok I see the issue - just need to change the let to var.
or const as var does not change - then build and it works

**Comment by ieshan** [comment]
Any plan to implement native scrolling feature ```scrollIntoView()```?

**Comment by DominikSerafin** [comment]
https://github.com/DominikSerafin/vuebar/issues/84

**Pull request closed without merging**
